### ISSUE TITLE
Nav generation does not ignore peer-scope topicrefs

### ISSUE THREAD

**Issue by drmacro** [dita4publishers/org.dita4publishers.html5#22]

**Comment by blefort** [comment]
Eliot, what is peer-scope topic refs?

**Comment by drmacro** [comment]
In DITA links, including topicrefs can specify the relationship of the target resource to the referencing resource using the @scope attribute:

- local (the default) means the target is part of the same publication (e.g., used from the same root map)
- external: The resource is not part of the current publication and completely separate (e.g., an external Web site or PDF document)
- peer: Not that well defined through DITA 1.2, but generally taken to mean "part of the same content set but not part of the current map," e.g., topics and maps managed together but published separately.

For DITA 1.3 we've defined a specific meaning for @scope="peer" on maprefs that also specify a key scope. It means that the target map is the root of a separate map tree and that references to keys in the peer map's scope are references to keys in that other root map, that is, cross-publication links.

**Comment by blefort** [comment]
Ok, I get it. This is an important feature. I am wondering how the link should be rendered. 

For example, if we reference a map like  this:
```
<mapref href="documentation.ditamap" scope="peer" />
```
Same for a topic that belong to another documentation.

**Comment by drmacro** [comment]
The map reference itself has no direct rendition implication: it simply establishes the relationship between the two root maps. Links within topics that point to keys within the peer map would be rendered like any other link.

For the purposes of the Oculus stuff I'm using the peer map references to construct navigation links to the target publications in the specific context of the transform that generates the index.html file for the Documentation Web site.

**Comment by blefort** [comment]
Ok
