### ISSUE TITLE
Previous and Next links on chunked content

### ISSUE THREAD

**Issue by blefort-uo** [dita4publishers/org.dita4publishers.html5#26]
@drmacro Need your help with that one!

The Previous and Next links resolution on this file
https://github.com/dita4publishers/org.dita4publishers.html5/blob/master/xsl/reltable.xsl

Do not work, because it does not check if a topiref is a result of a chunk

Also there are different kind of chunk, but I am far to have understand all aspects of @chunk, which I find personally complex to understand.

In the code, for example, on line 227, we have:

```xml
$topicref/preceding::*[df:isTopicRef(.)][1] | $topicref/ancestor::*[df:isTopicRef(.)][1])[last()]
```

Do you think the expression should be something like:

```
$topicref/preceding::*[df:isTopicRef(.)][not(@chunk)][1] | $topicref/ancestor::*[df:isTopicRef(.)][not(@chunk)][1])[last()]
```
Also the templates are used in jsAndCss.xsl to pass the info to the javascript d4p object.

I used your great example of chunking content in the test directory.

**Comment by drmacro** [comment]
Fixed. Added new function df:isNavigationTopicref() (will move this function of dita-utils at some point).
