### ISSUE TITLE
Specifying max navigation depth

### ISSUE THREAD

**Issue by mstanleyjones** [dita4publishers/org.dita4publishers.html5#33]
I've been trying to override the max navigation depth of 5, by passing `-Dd4p.max.nav.depth=12 -Dd4p.max.toc.depth=12` to ant, and adding them both to the transform properties in Oxygen, but I can't see that the properties are taking effect all. I have topics that are at a depth of 6 or 7 (it's hard to tell which) and they are not showing up in the navigation. I've been trying to figure this out for a couple days, and not finding much on Google. Also, if I wanted to change the defaults for these (once I figure out exactly what to pass), would I add them to the `parameters.xsl` in the plugin?

**Comment by blefort** [comment]
Let me have a look, the code has been done a long time ago ans was based on the html2 plugin. I can't remember there was a limitation.

**Comment by blefort** [comment]
The xls param which seems to control this is `maxTocDepth`
You can find it line 137 in `xsl/map2html5Impl.xsl`

However, it seems that the param is not part of the `parameters.xml` ant code, but I can add it.
I could probably fix it today.

Where did you find the `d4p.max.nav.depth` information?

**Comment by blefort** [comment]
Ok, I just added the ant property  `d4p.max.toc.depth`, so you should be able to by-pass the default limit of 5.

**Comment by mstanleyjones** [comment]
Thanks. I found the parameter at http://www.dita4publishers.org/d4p-users-guide/user_docs/d4p-users-guide/epub-plugin/reference/ant-parm-d4pMaxNavDepth.html. I finally did find the right place to put the XSL to override it for our customization, but I would rather pass it to Ant, at least for testing.

**Comment by blefort-uo** [comment]
Ok, thank you for letting me know. I did some researche and I think realized that was probably the best name since it was already in use.

Thank you for having reported the issue.
