### ISSUE TITLE
Remove dependency on HTML2 plugin by moving any HTML2-provided code

### ISSUE THREAD

**Issue by drmacro** [dita4publishers/org.dita4publishers.html5#39]
Either move the code into the HTML5 plugin or into a new common plugin.

**Comment by blefort** [comment]
I removed the dependency on the xsl 2 code a while ago, but I did not import any customization code that the HTML2 plugin will add on all XHTML based transform. I will have a look.

**Comment by blefort** [comment]
I double check and the HTML2 plugin relies entirely on the org.dita4publishers.common.html plugin, so I think this is already done.
