### ISSUE TITLE
toc="no" on <topicref> causes CSS formatting to be removed

### ISSUE THREAD

**Issue by markgif** [dita4publishers/org.dita4publishers.html5#67]
If I add toc="no" to a topicref like this:

<topicref href="topics/may_19_2017_rel_notes.xml" toc="no"/>

Then all HTML under that branch of the map become unstyled. I'm calling the dita2d4p-html5 target from my plugin and I'm not positive my plugin is not causing this, but has anyone seen this behavior with d4p html5?

**Comment by drmacro** [comment]
I haven't seen that behavior but adding toc="no" is probably pretty rare for most HTML5 users.

**Comment by drmacro** [comment]
I couldn't find any code that operated on @toc that isn't involved directly in navigation generation.

**Comment by markgif** [comment]
Thanks Eliot, you're right. Upon further investigation, the problem is in a plugin that overrides dita2d4p-html5.
